config/routes.rb
Rails.application.routes.draw do
  resources :sessions, only:[:new, :create, :destroy]

  resources :users

  match '/signup',  to: 'users#new',               via: 'get'
  match '/signin',  to: 'sessions#new',            via: 'get'
  match '/sessions/create', to: 'sessions#create', via: 'post'
  match '/signout', to: 'sessions#destroy',        via: 'delete'

  root to: 'static_pages#home'
  match '/about', to: 'static_pages#about', via: 'get'

  resources :todos
  match 'todos/:id/toggle_completed', to: 'todos#toggle_completed', via: 'get'

end

app/models/todo.rb
class Todo < ActiveRecord::Base
  belongs_to :user
  validates :title, presence: true

  before_save :default_values

  private

  def default_values
    self.completed ||= false
    nil                           # required so that TX will not rollback!!!
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :signed_in_user
  before_action :verify_correct_user, only: [:show, :edit, :update, :destroy]
  before_action :set_todo, only: [:toggle_completed, :show, :edit, :update, :destroy]

  # GET /todos
  # GET /todos.json
  def index
    @todos = current_user.todos.order(created_at: :desc)
  end

  # GET /todos/1
  # GET /todos/1.json
  def show
  end

  # GET /todos/new
  def new
    @todo = Todo.new
  end

  # GET /todos/1/edit
  def edit
  end

  # POST /todos
  # POST /todos.json
  def create
    @todo = Todo.new(todo_params)
    @todo.user = current_user

    respond_to do |format|
      if @todo.save
        format.html { redirect_to todos_path, notice: 'Todo was successfully created.' }
        format.json { render :show, status: :created, location: @todo }
      else
        format.html { render :new }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todos/1
  # PATCH/PUT /todos/1.json
  def update
    respond_to do |format|
      if @todo.update(todo_params)
        format.html { redirect_to todos_path, notice: 'Todo was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo }
      else
        format.html { render :edit }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todos/1
  # DELETE /todos/1.json
  def destroy
    @todo.destroy
    respond_to do |format|
      format.html { redirect_to todos_path, notice: 'Todo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def toggle_completed
    @todo.completed = !@todo.completed
    respond_to do |format|
      if @todo.save
        format.html { redirect_to todos_path }
        format.json { render :show, status: :ok, location: @todo }
      else
        # show some error message
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo
      @todo = Todo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_params
      params.require(:todo).permit(:title, :completed)
    end

    def verify_correct_user
      @todo = current_user.todos.find_by(id: params[:id])
      redirect_to root_url, notice: 'Access Denied!' if @todo.nil?
    end
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/todos/_form.html.erb
<%= form_for(@todo, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @todo.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@todo.errors.count, "error") %> prohibited this todo from being saved:</h4>

      <ul>
      <% @todo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :title, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :completed, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.check_box :completed, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/todos/edit.html.erb
<div class="page-header">
  <%= link_to todos_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @todo, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing todo</h1>
</div>

<%= render 'form' %>

app/views/todos/index.html.erb
<div class="page-header">
  <%= link_to new_todo_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Todo
  <% end %>
  <h1>Here are your TODOs</h1>
</div>

<div class="table-responsive todos">
  <table class="table table-hover">
    <thead>
      <tr>
        <th>Title</th>
        <th>Completed</th>
        <th>Show</th>
        <th>Edit</th>
        <th>Destroy</th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @todos) do |todo| %>
            <td><%= todo.title %></td>
            <!-- <td><%= todo.completed %></td> -->
            <td>
            <%= link_to("/todos/#{todo.id}/toggle_completed") do %>
              <% if todo.completed %>
                <span class="glyphicon glyphicon-ok"></span>
              <% else %>
                <span class="glyphicon glyphicon-unchecked"></span>
              <% end %>
             <% end %>
            </td>
            <td><%= link_to 'Show', todo %></td>
        <td><%= link_to 'Edit', edit_todo_path(todo) %></td>
        <td><%= link_to 'Destroy', todo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/todos/new.html.erb
<div class="page-header">
  <%= link_to todos_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New todo</h1>
</div>

<%= render 'form' %>

app/views/todos/show.html.erb
<div class="page-header">
  <%= link_to todos_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_todo_path(@todo), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show todo</h1>
</div>

<dl class="dl-horizontal">
  <dt>Title:</dt>
  <dd><%= @todo.title %></dd>

  <dt>Completed:</dt>
  <dd><%= @todo.completed %></dd>

  <dt>Created:</dt>
  <dd><%= @todo.created_at %></dd>
</dl>